# Generated by Django 5.0 on 2023-12-27 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("task", "0004_rename_name_tag_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="tag",
            field=models.ManyToManyField(blank=True, null=True, to="task.tag"),
        ),
    ]
